name: Flashy CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - '**.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'Procfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      NODE_ENV: development


    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Compile TypeScript
        run: npm run build

  deploy:
    needs: ["build"]
    runs-on: ubuntu-latest
    environment: heroku-general
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      - run: git push heroku master
